name: Deploy website 🚀

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ['main']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

inputs:
  name:
    description: 'Artifact name'
    required: false
    default: 'github-pages'
  retention-days:
    description: "Duration after which artifact will expire in days."
    required: false
    default: "1"

outputs:
  artifact_id:
    description: "The ID of the artifact that was uploaded."
    value: ${{ steps.upload-artifact.outputs.artifact-id }}

jobs:
  deploy:
    if: github.repository == 'PyNorte/pynorte2024-site'
    environment:
      name: production
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Build
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        id: upload-artifact
        uses: actions/upload-pages-artifact@v4
        with:
          # Upload dist repository
          path: './dist'
          name: ${{ inputs.name }}
          retention-days: ${{ inputs.retention-days }}
          if-no-files-found: error

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
